### ISSUE TITLE
動的に追加されたクラスでは動作しない？

### ISSUE THREAD

**Issue by YukiNishide** [yubinbango/yubinbango#15]
javasciptで後から動的に追加したclass="h-adr"では動作しませんか？
生成されたコードをそのままコピペで貼ったところ動作しましたが、
動的に生成したものでは動きませんでした。

**Comment by karak** [comment]
事後に `new YubinBango.MicroformatDom();` を実行すると動的に追加した form 要素でも動作しました。参考までに。
