### ISSUE TITLE
1つ郵便番号に複数の町が存在するケース

### ISSUE THREAD

**Issue by k-sakoda** [yubinbango/yubinbango#19]
日本郵政 
福島県 > 岩瀬郡鏡石町の郵便番号一覧
http://www.post.japanpost.jp/cgi-zip/zipcode.php?pref=7&city=1073420&addr=&cmp=1&mode=list

yubinbango
969-xxxx
https://yubinbango.github.io/yubinbango-data/data/969.js

例)
969-0402の場合、町域が複数存在しているがyubinbangoサイドには```"9690402":[7,"岩瀬郡鏡石町","池の台"]```しか存在しない

**Comment by koba-ninkigumi** [comment]
まず郵便番号は"配達"のための番号であることをご理解ください。
（位置情報としての利用であれば緯度経度やpunycodeを利用するのが良いでしょう）

yubinbangoライブラリでは、町域が複数存在している場合は、日本郵便のデータで最初に登場するデータを表示する「仕様」です。

そもそも同一の郵便番号に町域が複数存在しているケースについては、郵便番号が3桁から7桁になった際に、すべての町域に固有の郵便番号を割り当てることもできたも関わらず、配達する側としては区別する必要がないから同一の郵便番号が割り当てられているわけです。

郵便番号は、ひとつのビルに対して固有のひとつの番号が割り当てられている例も多数ありますので、もしも住民が区別したい事情があるのであれば、日本郵便に申し入れてみてください。

現状としてはこれらの地域は、たとえ町域が間違っていても配達に支障はないとの判断で日本郵政が番号を割り振っています。（心配しなくても配達に支障がある場合はその町域に固有の番号が割り当てられます。そしてyubinbangoライブラリには最新の郵便番号データが反映されます）
