### ISSUE TITLE
複数町域にまたがる郵便番号の扱いについて

### ISSUE THREAD

**Issue by sheepsace** [yubinbango/yubinbango#3]
複数町域にまたがる郵便番号を入力した場合、とある1つの町域の住所がセットされますが、この優先順位はどのようになっているのでしょうか？
どの町域をセットするか、選択できるようになるご予定などはありますでしょうか…？
(参考：http://qiita.com/khirose/items/3a121656425fac7bb820)

例1) 452-0961 
愛知県 清須市 春日明河原
愛知県 清須市 春日一番割
愛知県 清須市 春日壱屋敷
愛知県 清須市 春日一本松
愛知県 清須市 春日稲荷
愛知県 清須市 春日杁前
愛知県 清須市 春日午
愛知県 清須市 春日落合
(以下略)

例2) 618-0000
京都府 乙訓郡大山崎町
大阪府 三島郡島本町

**Comment by koba-ninkigumi** [comment]
まず大前提として。
郵便番号は、その名称通り、郵便（配達）を目的とした番号であるとの認識です。
他の用途、例えば"場所"や"範囲"を情報として扱う場合には、緯度経度や [plus+code](https://plus.codes/) を用いることをオススメします。

最初のご質問への回答です。
A1. 現在の優先順位は日本郵便株式会社が提供しているデータ中で最初に出現する町名となっています。

次の質問に回答する前に。
（ご指摘いただいた課題への対応を検討するに当たり下記の質問にご回答ください）

まず前提として。
例えば、清須市春日のケースは2009年まではすべて同一のひとつの町名でした。
これが行政によって住所の名称が変更されたあと、現在はまだそれぞれの住所に個別の郵便番号が割り振られていない"過渡期"の状態であるとの認識です。
しかし、もともと郵便番号を区別しなくても配達に不都合はなかった区域であり、もしも郵便番号と紐づく住所が異なることで問題が生じるのであれば新住所と旧住所の併用期間においてなんらかの混乱が生じるはずであり、結果としてもっと早い時期に個別に郵便番号が割り当てられていたはずですが、これがないということは（少なくとも配達上は）この地域に関わる方々は、例え郵便番号と紐づく住所が異なっていてもまったく不都合を感じていないことになります。

質問です。
Q1. これらの地域（住所名が異なるのに郵便番号がひとつの区域）において、郵便番号と紐づく住所が本来のものと異なっていて問題が生じるユースケースをなにかご存知でしょうか？

（もし区別の必要性があることをご説明いただけましたら、日本郵便株式会社に対して個別の郵便番号を割り振るように要望いたします）

**Comment by sheepsace** [comment]
お忙しいところご回答ありがとうございます！
優先順位について理解できました。

頂いたご質問への回答です。
以前あるフォームでライブラリを使用させて頂いたのですが、その際にまさにこの「452-0961」の郵便番号の方から応募がありました。
無知でお恥ずかしいのですが、その際初めて1つの郵便番号が1つの町域を特定できるものではないことを知りました。
それで、郵便番号でどの程度住所が絞り込めるかを調べていたところ、郵便局の下記ページに辿りつきました。

住所の記載省略は、どのようにすればよいのですか？
https://www.post.japanpost.jp/question/35.html

> 住所の一部を省略する際の注意点
> 正しい7桁の郵便番号であることを確認してください。
> 町域以下は必ず記載してください。

町域以下は必ず記載する必要があるということは、郵便番号が同じ町域が複数ある場合、それらの町域間で丁目や番地や号の重複があるのかなと考えました。
なので、郵便番号からセットされた町域までの住所が実際と異なる場合、別の町域の同じ丁目や番地や号の住所に配達されてしまう可能性があるのかな…と。
ただおっしゃる通り、2009年から個別郵便番号が割り当てられないことを考えると、特にそういう問題はない感じなのでしょうか…
