### ISSUE TITLE
都道府県の項目がセレクトボックスでvalue値が都道府県コードの場合

### ISSUE THREAD

**Issue by ghost** [yubinbango/yubinbango#4]
都道府県の項目がセレクトボックスで
value値が都道府県コードの場合について、
現状だとnull選択になるようです。

p-regionに「region_id」を渡せばよいと思いますが、現状のとかぶってしまう為、
別のclass名などを追加して渡せれば解決する気がします。

**Comment by koba-ninkigumi** [comment]
郵便番号を手入力させた後に都道府県をセレクトボックスから選択させるユースケースが思い浮かばないので教えてください。
そのためにコード量を増やすだけの需要があるかで判断したいと思います。

単に都道府県名から [全国地方公共団体コード](http://www.soumu.go.jp/denshijiti/code.html) への変換を行いたいだけなら、p-regionのinputにaddEventListenerのchangeで記述してはいかがでしょうか？

**Comment by koba-ninkigumi** [comment]
`<script src="https://koba-ninkigumi.github.io/yubinbango/yubinbango.js" charset="UTF-8"></script>`

@ActiveFusions とりあえず実験的に実装してみましたので、↑こちらのコードで期待通りの動作になっているか検証していただけますか？

**Comment by ghost** [comment]
お忙しいところご回答ありがとうございます！

軽く見ただけの為、申し訳ないのですが
どの辺のコードが変わって、都道府県コードで受け取れるようになったのか少しイメージしづらい状況です。
後日、詳しく見てみようと思います。

ただ、別の事で「yubinbango」を使うと「ajaxzip3」の様にclassやnameの指定ができない為、簡単にいかないかもしれない部分があるのではと考察したため再検討をしているところです。
※yubinbango.jsとは別にカスタマイズ用jsを書けばいいのは理解しています。

①ajaxzip3の様に複数住所を入力する場合、
例：請求者住所＋お届け先住所
にカスタマイズ用のjsを書く必要があるため。
→　ajaxzip3は郵便番号欄と対応する住所欄を指定できたため、便利でした。

**Comment by koba-ninkigumi** [comment]
@ActiveFusions YubinBangoは formタグで囲われた部分が自動的に反映されるので、複数の住所を入力する際にも動作します。

YubinBangoでclassやnameの指定は自由に任意の値を設定できます。
classの指定は、class="abc def p-region-id"のように既存のclass設定に追加すれば良いだけです。

念のため、動作しない（とお考えの）HTMLのサンプルをご掲示いただけますか？

**Comment by k1979** [comment]
こんにちは、初めまして。
大変便利に使わせて頂いております。
ありがとうございます。
複数の住所入力の件について調べていたところ、こちらが見つかりましたので質問をさせて頂きます。

classの指定の件については理解しておりますが、フォーム内に複数の住所を入力する際にはどのようにしたら良いのでしょうか？
例えば商品の発送の際に、ギフトなどで、お届け先の住所と、送り主の住所が異なる場合、二セットの入力欄が必要になる場合があります。

A
お届け先郵便番号：xxx-xxxx
お届け先住所：hoge

B
送り主郵便番号：yyy-yyyy
送り主住所：hogehoge

ajaxzip3の場合はnameによる指定が出来るので、現在はajaxzip3を使わせて頂いております。
YubinBangoの方でもカスタマイズの必要なく使えるのでしょうか？
あまり知識がなく、addClassとremoveClassを使って出力先inputの切り替えを試してみましたが、うまく作動しませんでした。
ご教示頂ければ幸いです。

**Comment by koba-ninkigumi** [comment]
こんにちは。

およそのイメージですが

<form>
<div class="h-adr">
<span class="p-country-name" style="display:none;">Japan</span>
〒<input name="お届け先の住所の郵便番号" type="text" class="p-postal-code" size="8"
maxlength="8"><br>
<input name="お届け先の住所" type="text" class="p-region p-locality
p-street-address p-extended-address" /><br>
</div>
<div class="h-adr">
<span class="p-country-name" style="display:none;">Japan</span>
〒<input name="送り主の住所の郵便番号" type="text" class="p-postal-code" size="8"
maxlength="8"><br>
<input name="送り主の住所" type="text" class="p-region p-locality
p-street-address p-extended-address" /><br>
</div>
</form>

こんな感じで設定します。（伝わりますかね？）

できたら代わりにもっとわかりやすく説明を書いてもらえるとありがたいです。

よろしくお願いします。



2017年2月19日 11:30 k1979 <notifications@github.com>:

**Comment by koba-ninkigumi** [comment]
およそのイメージですが

<form>
<div class="h-adr">
<span class="p-country-name" style="display:none;">Japan</span>
〒<input name="お届け先の住所の郵便番号" type="text" class="p-postal-code" size="8" maxlength="8"><br>
<input name="お届け先の住所" type="text" class="p-region p-locality p-street-address p-extended-address" /><br>
</div>
<div class="h-adr">
<span class="p-country-name" style="display:none;">Japan</span>
〒<input name="送り主の住所の郵便番号" type="text" class="p-postal-code" size="8" maxlength="8"><br>
<input name="送り主の住所" type="text" class="p-region p-locality p-street-address p-extended-address" /><br>
</div>
</form>

こんな感じで設定します。（伝わりますかね？）
できたら代わりにもっとわかりやすく説明を書いてもらえるとありがたいです。

よろしくお願いします。

**Comment by koba-ninkigumi** [comment]
@k1979 See -> https://github.com/yubinbango/yubinbango/issues/7#issuecomment-280972433
