### ISSUE TITLE
郵便番号796-0088の問題

### ISSUE THREAD

**Issue by mengdq** [yubinbango/yubinbango#5]
郵便番号を入力すると正しい住所が
セットされない。

郵便番号：796-0088

愛媛県八幡浜市八幡浜市と表示される

本来は、愛媛県八幡浜市の次にはすぐに番地になる。
郵便局のサイトで確認すると、正しい表示になっているんですが。

**Comment by koba-ninkigumi** [comment]
対応しました。ご確認ください。
ご報告ありがとうございます。

**Comment by mengdq** [comment]
ご対応ありがとうございます。
差し支えなければ、
原因を教えていただけませんか。

2016-07-22 12:16 GMT+09:00 小林照幸 notifications@github.com:

**Comment by koba-ninkigumi** [comment]
こちら正確にはyubinbangoの不都合ではなく、[yubinbango-data](https://github.com/yubinbango/yubinbango-data) のデータの変更となります。

郵便局の元データが
◯◯の次に番地がくる場合 （7960088の場合、"八幡浜市の次に番地がくる場合"）
なら、これまでは
◯◯ （7960088の場合、"八幡浜市"）
と変換する仕様でした。

これを
◯◯
の部分まで含めて削除するように仕様変更いたしました。

**Comment by mengdq** [comment]
ご連絡ありがとうございます。
了解しました。

2016年7月24日 19:20 小林照幸 notifications@github.com:
