### ISSUE TITLE
動的に表示されたフォームでの利用

### ISSUE THREAD

**Issue by kntmrkm** [yubinbango/yubinbango#6]
通常のHTML読み込み後には動作したのを確認後（なので設定等は問題無いと思います）に、

TwitterのCSSフレームワークBootstrapでのModalに、
Ajaxで動的にフォームを表示させるケースで使うと動作しません。

Ajaxで動的に表示したフォームに対してyubinbangoを動かすために、
意図的なyubinbangoの初期化処理等はできますか？

**Comment by koba-ninkigumi** [comment]
domを用意した後で

```
new YubinBango.MicroformatDom();
```

を呼び出してください。
