### ISSUE TITLE
複数の住所入力

### ISSUE THREAD

**Issue by ShulliDrake** [yubinbango/yubinbango#7]
一つのフォームに複数の住所を入力するケースへの対応予定はありますか？
(例えば、送付先と請求書先に違う住所を入力する場合など)

**Comment by koba-ninkigumi** [comment]
年末年始で対応してみますのでテストに協力していただける方はこちらにコメントをお願いします。

**Comment by primestyleus** [comment]
1月半ばに公開するサイトで住所入力がフォーム内に3つあるページがあります。もし対応予定でしたら、テストにぜひ協力させてください。 @koba-ninkigumi

**Comment by koba-ninkigumi** [comment]
テストしていただける方はこちらを利用してみてください。

    https://koba-ninkigumi.github.io/yubinbango/yubinbango.js


使用例です。

    <form>
      <div class="h-adr">
        住所1
      </div>
      <div class="h-adr">
        住所2
      </div>
    </form>

**Comment by primestyleus** [comment]
@koba-ninkigumi 動作確認しました。問題なく動いております。

**Comment by mtakorz** [comment]
確認しました、問題ないようです。

**Comment by koba-ninkigumi** [comment]
@k1979 およそのイメージですが

    <form>
    <div class="h-adr">
      <span class="p-country-name" style="display:none;">Japan</span>
      〒<input name="お届け先の住所の郵便番号" type="text" class="p-postal-code" size="8" maxlength="8"><br>
      <input name="お届け先の住所" type="text" class="p-region p-locality p-street-address p-extended-address" /><br>
    </div>
    <div class="h-adr">
      <span class="p-country-name" style="display:none;">Japan</span>
      〒<input name="送り主の住所の郵便番号" type="text" class="p-postal-code" size="8" maxlength="8"><br>
      <input name="送り主の住所" type="text" class="p-region p-locality p-street-address p-extended-address" /><br>
    </div>
    </form>

こんな感じで設定します。（伝わりますかね？）
できたら代わりにもっとわかりやすく説明を書いてもらえるとありがたいです。

よろしくお願いします。

**Comment by k1979** [comment]
申し訳ありません、既に対応されていたものだったのですね。
検索不足で、お手数をおかけしました。

formタグにclass="h-adr"を指定するのではなく、入れ子のdiv等にclass="h-adr"を指定して、そこで括られた枠内で、郵便番号と住所のセットが一つ出来上がるイメージですね。

上手く説明出来るかはちょっと自信がないので、私が設置した際の別な例を貼らせて頂きます(最小限の記載のみですので、もしこんなものでもどなたか参考にされる際には各自カスタマイズして下さい)。

    <form>
      <fieldset>
        <legend>届け先の情報</legend>
    
          <ul class="h-adr">
            <li><span class="p-country-name" style="display:none;">Japan</span>
              <label>届け先郵便番号</label><input type="text" class="p-postal-code" />
            </li>
            <li>
              <label>届け先住所</label><input type="text" class="p-region p-locality p-street-address p-extended-address" />
            </li>
          </ul>
    
      </fieldset>
      <fieldset>
        <legend>送り主の情報</legend>
    
          <ul class="h-adr">
            <li><span class="p-country-name" style="display:none;">Japan</span>
              <label>送り主郵便番号</label><input type="text" class="p-postal-code" />
            </li>
            <li>
              <label>送り主住所</label><input type="text" class="p-region p-locality p-street-address p-extended-address" />
            </li>
          </ul>
    
      </fieldset>
    </form>
