### ISSUE TITLE
Turbolinksとの共存

### ISSUE THREAD

**Issue by kntmrkm** [yubinbango/yubinbango#8]
Railsフレームワーク内で利用させていただいています。

- https://github.com/turbolinks/turbolinks-classic

上記のturbolinksという機能で、ページを遷移後に`page:load`というイベントが発火するので、
以下の用に設定してみましたが、動作しません。
（以下の関数内の処理は実行されていることは確認しています。）

```
$(document).on('page:load', function() {
  new YubinBango.MicroformatDom();
});
```

turbolinksは`body`タグ内のDOMのみを入れ替える機能を持っています。
解決策はありますでしょうか。

**Comment by koba-ninkigumi** [comment]
railsもturbolinksも使っていないので違っていたらごめんなさい。page:loadというのはdomの描画完了前に発火するのではないですか？（当然ながらdomの描画完了前だとeventが付与されません）

turbolinksでDOMContentLoadedイベントに相当するのは、page:changeですかね？

**Comment by kntmrkm** [comment]
ありがとうございます。
おっしゃるように`DOMContentLoadedイベントに相当するのは、page:change`のようです。

> 'page:change'の動作
> 
> どんな場合でもページを表示した後に発火
> $(document).ready() 相当
> DOMContentLoaded リスナーに追加されている
> 発火タイミングは DOMContentLoaded + fetchReplacement + fetchHistory
> しかし、DOMContentLoadedはIE6,7など古いブラウザでは実装されていないので古いブラウザでも動作させたい処理を書くときは使用しない事。

が、`change`にしても動きませんでした。

以下の用に試してみて`new YubinBango.MicroformatDom();`の実行時にはDOMが存在することは確認できているのですが・・・

```
$.fn.exists = function(){return Boolean(this.length > 0); };

$(document).on('page:change page:restore', function() {
  console.log('YubinBango reinitialize.');
  console.log('.h-adr existence.', $('.h-adr').exists());
  new YubinBango.MicroformatDom();
});
```

**Comment by koba-ninkigumi** [comment]
turbolinksを使ってないのでそれ以上はわからないです。
ただturbolinksの挙動を見ると、xhrがある度にいろいろとやるライブラリみたいなので、jsonpで郵便番号データを取得する際に副作用があるのかも・・・？

サンプルコードをDockerに載せたものはありますか？

**Comment by kntmrkm** [comment]
目処が微妙ですが、dockerでの再現コード作ってみます。
ありがとうございます。

**Comment by kntmrkm** [comment]
https://github.com/kntmrkm/YubinBangoRails

`docker-compose up`で動くと思います（初dockerで不備があるかもしれません。）

## 再現手順

### 動作する

- `http://lvh.me:3000/posts/new`でブラウザからリロード

### 動作しない

- `http://lvh.me:3000/posts`でブラウザリロード
- `New Post`リンクから遷移後は動作しない

よろしくお願いいたします。

**Comment by kntmrkm** [comment]
@koba-ninkigumi

**Comment by kntmrkm** [comment]
@koba-ninkigumi 
共存は難しいでしょうか？

**Comment by koba-ninkigumi** [comment]
@kntmrkm 以前もお伝えした通り私はrailsもturbolinksも使っていません。（つまり私が無償でturbolinksに依存する対応コードを書くことはありません）
turbolinksに対応する改変がどんな良い影響を及ぼすのかわかりやすく説明した上でpull requestを送っていただくのであれば取り込む可能性もあります。

**Comment by kntmrkm** [comment]
@koba-ninkigumi 
uglify後のソースでは動きませんが、
Typescriptのコンパイル後のソースだと、Turbolinksで動くようになりました。

原因判明とまではいってませんが、一応ご報告まで。

**Comment by fullkawa** [comment]
turbolinks5では下記コードをコントローラ毎のスクリプトファイル(users.coffeeなど)に書いて動作させることができました。

```
document.addEventListener 'turbolinks:load', ->
  new YubinBango.MicroformatDom()
```

参考リンク
[Running JavaScript When a Page Loads](https://github.com/turbolinks/turbolinks#running-javascript-when-a-page-loads)
